
services:
  api:
    build:
      context: .
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - .env
    develop:
      watch:
        - path: requirements.txt
          action: rebuild
        - path: .
          target: /app
          action: sync
    networks:
      - my-app-network
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - media_data:/app/media
  db:
    image: postgres:17.3-alpine
    volumes:
      - db_data:/var/lib/postgresql/data

    environment:

      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}

    networks:
      - my-app-network

volumes:
  db_data:
  media_data:

networks:
  my-app-network:


