# Generated by Django 5.1 on 2024-08-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_management_app', '0004_assignment_assignmentsubmissiondetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmissiondetails',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmissiondetails',
            name='student',
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='AssignmentSubmissionDetails',
        ),
    ]
