# Generated by Django 5.1 on 2024-08-24 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_management_app', '0005_remove_assignmentsubmissiondetails_assignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_no', models.AutoField(primary_key=True, serialize=False)),
                ('assignment_title', models.CharField(max_length=100)),
                ('assignment_description', models.TextField()),
                ('posting_date', models.DateField(auto_now_add=True)),
                ('last_date_of_submission', models.DateField()),
                ('assignment_marks', models.IntegerField(default=-1)),
                ('assignment_file', models.FileField(upload_to='media/assignments/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_management_app.course')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_management_app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmissionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_description', models.TextField()),
                ('answer_paper', models.FileField(upload_to='media/submissions/')),
                ('remarks', models.TextField()),
                ('marks_obtained', models.IntegerField()),
                ('submitted_date', models.DateField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_management_app.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
