# Generated by Django 5.1 on 2024-08-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_management_app', '0006_assignment_assignmentsubmissiondetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmissiondetails',
            name='marks_obtained',
            field=models.IntegerField(default=-1),
        ),
    ]
