# Generated by Django 5.1 on 2024-08-27 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_management_app', '0009_studymaterial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyMaterial',
        ),
    ]
