# Generated by Django 5.1 on 2024-08-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_management_app', '0011_studymaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
