# Generated by Django 5.1 on 2024-08-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_management_app', '0012_alter_studymaterial_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
